name: 'build-test'

on:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: josStorer/get-current-time@v2.1.0
        id: current-time
        with:
          format: YYYYMMDD-HH
          utcOffset: "+08:00"
      - uses: ./
        with:
          token: ${{ secrets.token }}
          title: "PUSHPLUS推送"
          content: "PUSHPLUS推送 ${{ steps.current-time.outputs.formattedTime }}"

